### ISSUE TITLE
Help folks ignore bazel-* in .analysis_options

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/bazel#30]
See if a user has one, add the entries, etc...

**Comment by bwilkerson** [comment]
Those directories will also be ignored if the user opens a subdirectory of the root workspace directory, and I think that should be our advice. (https://github.com/dart-lang/bazel/issues/32)

**Comment by natebosch** [comment]
@bwilkerson Either we'd need to
1. Restructure this all so that the WORKSPACE sits a level up from the target package. I think this is a non-starter
or
2. Ask people to separately add `lib/`, `web/`, and `test/` to their intellij project

Does the analyzer ignore hidden directories by default? Maybe we should talk to the bazel team about whether we can change the `bazel-*` to `.bazel-*`

**Comment by bwilkerson** [comment]
> 1. Restructure this all so that the WORKSPACE sits a level up from the target package. I think this is a non-starter

Not sure why. That's what I would have expected we would recommend so that multiple packages could live in the same workspace. Don't you need that if you have a package P1 that depends on a package P2, so that you can tell Bazel about the dependencies and get it to build both packages?

> 2. Ask people to separately add lib/, web/, and test/ to their intellij project

I'm not sure whether that would even work, but it would certainly be a poor UX.

**Comment by kevmoo** [comment]
Our other option here is to assume there is an bazel plugin in intelliJ, which handles this – at least in theory

**Comment by natebosch** [comment]
>Not sure why. That's what I would have expected we would recommend so that multiple packages could live in the same workspace. Don't you need that if you have a package P1 that depends on a package P2, so that you can tell Bazel about the dependencies and get it to build both packages?

Yes, if you are working on multiple packages in the same workspace you'd need have the WORKSPACE at least 1 level up. We don't have a story yet for how to 'upgrade' to this type of work. I think also a `dependency_overrides` pointing to a local path *should* work which is I think how most users are doing this today.

We expect the majority of our users will be working on a single package so this is the use case we're tackling first. If we want WORKSPACE a level up we'd need to tell people to set things up in advance. We wouldn't be able to say 'take a directory you're already working in and bazelify it' - we'd have to say 'set up your folder structure like this, then bazelify it'

**Comment by bwilkerson** [comment]
> I think also a `dependency_overrides` pointing to a local path should work which is I think how most users are doing this today.

Are we planning on having both pubspec.yaml and BUILD files for every package? I was assuming that we would use the BUILD file rather than the pubspec.yaml. If the pubspec.yaml is there, then should we expect to have a `.package` file too?

And a mete-level question: is there documentation for what you expect this to look like when you're done?

> We expect the majority of our users will be working on a single package ...

This doesn't match my experience with the early adoptors of Dart, but my visibility primarily comes from issues and e-mails, so perhaps it's skewed.

> If we want WORKSPACE a level up we'd need to tell people to set things up in advance.

I added a description of a potential alternative to the Doc you sent me.

**Comment by devoncarew** [comment]
related: https://github.com/google/stagehand/issues/344
